processes:
  location:
    config_file: "location_config"
    date_csv_cols: "localtime"
  current:
    config_file: "current_config"
    date_csv_cols: "last_updated"
  forecast:
    config_file: "forecast_config"
    date_csv_cols: "date"