processes:
  location:
    table_name: "location"
    config_file: "location_config"
    date_csv_cols: "localtime"
  current:
    table_name: "current"
    config_file: "current_config"
    date_csv_cols: "last_updated"
  forecast:
    table_name: "forecast"
    config_file: "forecast_config"
    date_csv_cols: "date"