source:
  - location:
    - config_name: location_config
      date_csv_col: localtime
  # - current:
  #   - config_name: current_config
  #     date_csv_col: last_update
  # - forecast:
  #   - config_name: forecast_config
  #     date_csv_col: date
  