version: '3'

services:
  airflow:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__AIRFLOW_HOME=/opt/airflow
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - PYTHONPATH=/opt/project
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
      - ./:/opt/project:delegated
    working_dir: /opt/project
    ports:
      - "8080:8080"
    depends_on:
      # - postgres_airflow
      - postgres
      - minio
    command: ["bash","-c","exec airflow standalone"]

  # postgres_airflow:
  #   image: postgres:latest
  #   env_file:
  #     - .env
  #   environment:
  #     - POSTGRES_DB=${AIRFLOW_DB_NAME}
  #     - POSTGRES_USER=${AIRFLOW_DB_USER}
  #     - POSTGRES_PASSWORD=${AIRFLOW_DB_PASS}
  #   volumes:
  #     - postgres-airflow-data:/var/lib/postgresql/data
  #   ports:
  #     - "${AIRFLOW_DB_PORT}:5432"

  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_KMS_SECRET_KEY=${MINIO_KMS_SECRET_KEY}
    volumes:
      - minio-data:/data

  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.6.0
    container_name: dbt
    volumes:
      - ./dbt:/dbt
    working_dir: /dbt
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - postgres
  
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  # postgres-airflow-data:
  postgres-data:
  minio-data:
